Added classes from lesson 4
dimloko/javafirsttry pull request #1
Opened 2020-08-03 09:14 UTC by dimloko

Homework for lesson_4

2020-08-05 12:01 UTC, RomanKashenok requested changes

2020-08-05 12:01 UTC, RomanKashenok commented on project/src/Autor.java
> +        name = "Unknown";
don't assign anything if it's not required

2020-08-05 12:01 UTC, RomanKashenok commented on project/src/Autor.java
> +        dob = 0;
it'll be 0 by default. remove assignment

2020-08-05 12:01 UTC, RomanKashenok commented on project/src/Book.java
> +    public Book() {
the same comments as in Author

2020-08-05 12:01 UTC, RomanKashenok commented on project/src/Genre.java
> +    public Genre() {
the same as in Author

2020-08-05 12:01 UTC, RomanKashenok commented on project/src/Library.java
> +    public Library() {
the same as in Author

2020-08-05 12:01 UTC, RomanKashenok commented on project/src/Library.java
> +    int num_of_books; //Количество книг
numOfBooks instead of num_of_books

2020-08-05 14:37 UTC, dimloko commented on project/src/Library.java
> +    int num_of_books; //Количество книг
Done, hopefully right)

2020-08-07 18:28 UTC, TheFallen058 approved these changes

2020-08-16 17:06 UTC, RomanKashenok approved these changes
Fix a little according to comments and feel free t merge

2020-08-16 17:06 UTC, RomanKashenok commented on project/src/Genre.java
>      String genre_name; //Название жанра
genreName. not genre_name
and just "name" will be better

2020-08-20 17:22 UTC, merged